export const products = [
  {
    image: "/products/honey.png",
    name: "Natural Honey 250ml Honey",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: ["top", "popular", "flash"],
  },
  {
    image: "/products/honney2.png",
    name: "Unfiltered Honey - 1kg ",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: ["top", "popular"],
  },
  {
    image: "/products/ghee.png",
    name: "Fresh Ghee 500ml",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: ["top", "popular"],
  },
  {
    image: "/products/oil.png",
    name: "Royal Premium Canola Cooking Oil ",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: ["top", "popular", "flash"],
  },
  {
    image: "/products/honney2.png",
    name: "Unfiltered Honey - 1kg",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: ["top"],
  },
  {
    image: "/products/raw_honney.png",
    name: "Unfiltered Honey - 1kg",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: ["flash", "popular"],
  },
  {
    image: "/products/sorish_oil.png",
    name: "Unfiltered Honey - 1kg",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: ["flash"],
  },
  {
    image: "/products/mustard_oil.png",
    name: "Unfiltered Honey - 1kg",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: ["flash"],
  },
  {
    image: "/products/honey.png",
    name: "Natural Honey 250ml Honey",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: [],
  },
  {
    image: "/products/honey.png",
    name: "Natural Honey 250ml Honey",
    price: 499,
    firstPrice: 599,
    rating: 4.9,
    ml: 250,
    sub: [],
  },
];
